---
sidebar: sidebar 
permalink: get-started/capacity-login.html 
keywords: bluexp login, capacity planning log in 
summary: Der Service in BlueXP macht den Einstieg in die wirtschaftliche Effizienz von BlueXP möglich. 
---
= Profitieren Sie von der wirtschaftlichen Effizienz von BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Sie verwenden NetApp BlueXP, um sich an einem wirtschaftlichen Effizienz-Service anzumelden.

Zur Anmeldung bei BlueXP können Sie Ihre Zugangsdaten für die NetApp Support Website nutzen oder sich mithilfe Ihrer E-Mail und eines Passworts für eine NetApp Cloud-Anmeldung anmelden. https://docs.netapp.com/us-en/bluexp-setup-admin/task-logging-in.html["Erfahren Sie mehr über die Anmeldung"^].


TIP: Sie können auf diese Funktion entweder über die wirtschaftliche Effizienz von BlueXP (*Governance* > *wirtschaftliche Effizienz* > *Tech Refresh*) oder über den digitalen NetApp-Berater (*Dashboard* > *Planungs-Widget* > *Tech Refresh*) zugreifen.

.Schritte
. Öffnen Sie einen Webbrowser, und rufen Sie den auf https://console.bluexp.netapp.com/["BlueXP-Konsole"^].
+
Die Anmeldeseite für NetApp BlueXP wird angezeigt.

. Melden Sie sich bei BlueXP an.
. Wählen Sie in der linken Navigationsleiste von BlueXP *Governance* > *Economic Efficiency* aus.

