---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp economic efficiency works, what is economic efficiency, bluexp, hardware refresh, technology refresh, capacity, forecasted capacity, storage, forecast 
summary: Der BlueXP  Service zur wirtschaftlichen Effizienz identifiziert Cluster mit aktuell oder mit prognostizierter niedriger Kapazität und gibt Ihnen Empfehlungen für das Daten-Tiering. 
---
= Erfahren Sie mehr über die wirtschaftliche Effizienz von BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Die wirtschaftliche Effizienz von BlueXP  bewertet Ihre Storage-Assets anhand aktueller oder prognostizierter Kapazitäten. Der Service gibt Empfehlungen für die Daten-Tiering-Optionen, die Ihre Geschäftsanforderungen erfüllen.

Die wirtschaftliche Effizienz von BlueXP unterstützt Sie dabei, folgende Ziele zu erreichen.

*Kapazitätsplanung*

* Identifizieren Sie Storage-Assets in Ihrer Umgebung, die wenig Kapazität zeigen.
* Prüfen Sie Assets auf aktuelle und prognostizierte Kapazitäten.




== Vorteile der wirtschaftlichen Effizienz von BlueXP

Die wirtschaftliche Effizienz von BlueXP bietet folgende Vorteile:

* Identifiziert Systeme, die sich den Lebenszyklusereignissen nähern, um Sie bei der Planung einer Technologieaktualisierung zu unterstützen
* Bietet Empfehlungen eines vertrauenswürdigen Beraters zur Behebung von Kapazitätsproblemen in Ihrer Umgebung
* Weniger Zeitaufwand für die Planung von zusätzlichem Storage




== Kosten

NetApp berechnet Ihnen keine Kosten für die Nutzung des Service.

Wenn Sie kalte Daten auf Cloud-Storage verschieben möchten, müssen Sie Ihren Cloud-Provider prüfen, ob die Gebühren anfallen.



== Datenzugriff

Sie können auf diese Funktion entweder über die wirtschaftliche Effizienz von BlueXP (*Governance* > *wirtschaftliche Effizienz* > *Tech Refresh*) oder über den digitalen NetApp-Berater (*Dashboard* > *Planungs-Widget* > *Tech Refresh*) zugreifen.
