---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp economic efficiency works, what is economic efficiency, bluexp 
summary: 'Der BlueXP Service für wirtschaftliche Effizienz erkennt Cluster mit aktueller oder prognostizierter niedriger Kapazität und bietet Empfehlungen für Daten-Tiering oder zusätzliche Kapazität (für AFF Systeme).' 
---
= Erfahren Sie mehr über die wirtschaftliche Effizienz von BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Kapazitätsplanung ist wichtig, um unnötige Ausfallzeiten aufgrund geringer Systemkapazitäten zu vermeiden. Die wirtschaftliche Effizienz von BlueXP ermöglicht Ihnen Folgendes:

* Identifizieren Sie Storage-Assets in Ihrer Umgebung, die wenig Kapazität zeigen.
* Prüfen Sie Assets auf aktuelle und prognostizierte Kapazitäten.
* Prüfen Sie die CPU-Auslastung, IOPS-Performance und Latenz-Performance, um Möglichkeiten zur Behebung von Kapazitätsremaßnahmen zu ermitteln.


Die wirtschaftliche Effizienz von BlueXP ermittelt Storage-Assets mit aktueller oder prognostizierter niedriger Kapazität und gibt Empfehlungen für Daten-Tiering oder zusätzliche Kapazität (für AFF Systeme). Wenn Sie sich für eine Erweiterung der Kapazität entscheiden, wird eine Anfrage mit detaillierten Empfehlungen an Sie und einen NetApp Vertreter weitergeleitet. Diese Anfrage enthält alle Details, die erforderlich sind, um die Kapazitätsauswahl und Bestellanfrage zu vereinfachen.

Auf den Service kann in BlueXP unter der Kategorie *Governance* zugegriffen werden.

Die wirtschaftliche Effizienz von BlueXP bezieht sich ausschließlich auf lokale AFF Systeme (einschließlich Unified AFF und alle SAN-Array-Systeme).



== Vorteile der wirtschaftlichen Effizienz von BlueXP

Die wirtschaftliche Effizienz von BlueXP bietet folgende Vorteile:

* Zusätzlicher Kapazität lässt sich durch einen einfachen Prozess ermitteln
* Bietet Ihnen einen zuverlässigen Berater und Empfehlungen zur Behebung von Kapazitätsproblemen in Ihrer Umgebung
* Weniger Zeitaufwand für die Planung von zusätzlichem Storage




== Kosten

NetApp berechnet Ihnen keine Kosten für die Nutzung des Service. Wenn Sie kalte Daten auf Cloud-Storage verschieben möchten, müssen Sie Ihren Cloud-Provider prüfen, ob die Gebühren anfallen.
