---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp economic efficiency requirements, economic efficiency prerequisites 
summary: 'Erste Schritte mit der wirtschaftlichen Effizienz von BlueXP: Überprüfen Sie den Support für Ihre Umgebung, Ihren Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser.' 
---
= Voraussetzungen für die wirtschaftliche Effizienz von BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Prüfen Sie zunächst die Bereitschaft Ihrer Betriebsumgebung, Anmeldung und des Netzwerkzugriffs.

Um die wirtschaftliche Effizienz von BlueXP zu nutzen, sollten Sie sicherstellen, dass Ihre Umgebung alle Anforderungen erfüllt.

* Ihre Umgebung muss alle BlueXP Anforderungen erfüllen – einschließlich Anmeldung und Netzwerkzugriff über einen Webbrowser.
+
Siehe https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["BlueXP Quick Start Guide"^] Und https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html["BlueXP Netzwerkinformationen"^].

* Sie müssen über die Zugangsdaten für die Cluster verfügen.
* Es ist zwar keine Voraussetzung, aber hilfreich, wenn der BlueXP Connector vorhanden und aktiviert ist und das ONTAP System erkannt wird. Falls nicht, führt Sie der Service durch diese Prozesse.
* Wenn Sie Tiering von kalten Daten in Cloud-Storage planen, stellen Sie sicher, dass das Cluster entsprechend der Lizenz berechtigt ist.

