---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: economic efficiency faq, bluexp, economic efficiency frequently asked questions 
summary: 'Der BlueXP Service für wirtschaftliche Effizienz erkennt Cluster mit aktueller oder prognostizierter niedriger Kapazität und bietet Empfehlungen für Daten-Tiering oder zusätzliche Kapazität (für AFF Systeme). Der Service bietet außerdem Empfehlungen zur Technologieaktualisierung für Systeme, die sich dem Ende ihres Lebenszyklus nähern.' 
---
= Was ist neu
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Neuerungen bei der wirtschaftlichen Effizienz von BlueXP.



== 15 Mai 2024

Einige der BlueXP  Funktionen zur wirtschaftlichen Effizienz wurden vorübergehend deaktiviert:

* Technologieaktualisierungen
* Kapazitäten ergänzen




== 14 März 2024

Wenn Sie bereits über Assets verfügen und feststellen möchten, ob eine Technologie aktualisiert werden muss, können Sie die wirtschaftlichen Effizienzoptionen von BlueXP nutzen. Sie können entweder eine kurze Bewertung Ihrer aktuellen Workloads überprüfen und Empfehlungen erhalten, oder wenn Sie in den vergangenen 90 Tagen AutoSupport-Protokolle an NetApp gesendet haben, kann der Service jetzt eine Workload-Simulation durchführen, um die Performance Ihrer Workloads auf neuer Hardware zu ermitteln.

Sie können auch einen Workload hinzufügen und vorhandene Workloads von der Simulation ausschließen.

Bisher konnten Sie nur eine Bewertung Ihrer Ressourcen vornehmen und feststellen, ob eine Technologieerneuerung empfohlen wird.

Die Funktion ist jetzt Teil der Option „Tech Refresh“ in der linken Navigation.

Erfahren Sie mehr über das link:../use/tech-refresh.html["Bewertung einer Technologieaktualisierung"].



== Bis 08. November 2023

Diese Version der wirtschaftlichen Effizienz von BlueXP enthält eine neue Option, mit der Sie Ihre Assets bewerten und feststellen können, ob eine Technologieaktualisierung empfohlen wird. Der Service umfasst eine neue Option zur technischen Aktualisierung in der linken Navigation, neue Seiten, auf denen Sie eine Bewertung Ihrer aktuellen Workloads und Ressourcen vornehmen können, sowie einen Bericht mit Empfehlungen für Sie.



== Bis 02. April 2023

Der neue BlueXP Service für wirtschaftliche Effizienz erkennt Storage-Assets mit aktueller oder prognostizierter niedriger Kapazität und gibt Empfehlungen zu Daten-Tiering oder zusätzlicher Kapazität für lokale AFF Systeme.

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html["Erfahren Sie mehr über die wirtschaftliche Effizienz von BlueXP"].
